### ISSUE TITLE
Registry admin command must not modify the SCC

### ISSUE THREAD

**Issue by ncdc** [projectatomic/atomic-enterprise#44]
It's ok if the registry admin command creates a `registry` service account to use when running the registry, but it must not add it to the privileged SCC. This gives that service account superuser privileges by default, which is something an admin should make a careful decision about.

**Comment by ncdc** [comment]
@liggitt

**Comment by ncdc** [comment]
@ashcrow @giuseppe

**Comment by liggitt** [comment]
in addition to the fundamental issue that the registry command should not be modifying policy or security settings, the "privileged" SCC is not guaranteed to exist... that's just an out of box default name, but cluster admins are free to modify or delete it

**Comment by ashcrow** [comment]
@liggitt @ncdc understood. We'll remove the SCC portion.

**Comment by ashcrow** [comment]
@liggitt @ncdc actually, let me take a step back and ask if a service account is actually required for the registry to work. If not we will just revert the change. If so, why shouldn't we allow the user to create a service account (assuming non privileged) at the time of registry creation?

**Comment by liggitt** [comment]
If no service account is specified, the default one is used. I don't think this command should be creating service accounts… that should probably be a separate command

**Comment by ashcrow** [comment]
@liggitt ok, good to know. Thanks for the info. I'll revert the change.

**Comment by ashcrow** [comment]
Revert PR https://github.com/projectatomic/atomic-enterprise/pull/46
